### ISSUE TITLE
Errore con calibrazione 

### ISSUE THREAD

**Issue by giulianamilluzzo** [INFN-LNS/I-LUCE#1]
Quando provo gli rcf unlaminated calibrati a legnaro e anche la calibrazione degli EBT3, mi da quest'errore e non fa nè il fit né il grafico:

Error using RCFPolynomialFit
Too many output arguments.

**Comment by cirrone** [comment]
@giulianamilluzzo questo è stato risolto? se si, chiudo lo issue

**Comment by giulianamilluzzo** [comment]
sisi risolto
